routes/web.php
<?php


Auth::routes();

Route::resource('transactions', 'Transactions\TransactionsController', ['except' => ['show']]);
Route::get('/transactions/{category?}', 'Transactions\TransactionsController@index');

Route::resource('categories', 'Categories\CategoriesController')->middleware('auth');

Route::resource('budgets', 'Budgets\BudgetsController')->middleware('auth');

app/Models/Budget/Budget.php
<?php

namespace App\Models\Budget;

use App\Models\Scopes\BudgetScope;
use App\Models\Scopes\UserScope;
use App\Models\Transactions\Category;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Budget extends Model
{
    protected $fillable = ['category_id', 'amount', 'user_id', 'budget_date'];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new UserScope);
        static::addGlobalScope(new BudgetScope);

        static::saving(function($budget) {
            $budget->user_id = $budget->user_id ?: auth()->id();
            $budget->budget_date = Carbon::parse($budget->budget_date)->toDateTimeString();
        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function balance()
    {
        return ($this->amount - $this->category->transactions->sum('amount'));
    }

    public function scopeByMonth($query, $month)
    {
        $query->where('budget_date', '>=', Carbon::parse("first day of {$month}"))
            ->where('budget_date', '<=', Carbon::parse("last day of {$month}"));
    }

    public function getMonth()
    {
        return (isset($this->budget_date)) ? Carbon::parse($this->budget_date)->format('M') : null;
    }
}

app/Http/Controllers/Budgets/BudgetsController.php
<?php

namespace App\Http\Controllers\Budgets;

use App\Models\Budget\Budget;
use App\Models\Transactions\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;

class BudgetsController extends Controller
{

    protected $months = ['Jan','Feb', 'Mar','Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

    public function index()
    {
        $currentMonth = request('month') ?: Carbon::now()->format('M');
        $budgets = Budget::byMonth($currentMonth)->get();
        $months = $this->months;
        return view('budgets.index', compact('budgets', 'currentMonth', 'months'));
    }


    public function create()
    {
        $categories = Category::all();
        $months = $this->months;
        return view('budgets.create', compact('categories', 'months'));
    }


    public function store()
    {
        $this->validate(request(), [
            'budget_date'=>'required', 'category_id'=>'required', 'amount'=>'required']);
        Budget::create(request()->all());
        return redirect(route('budgets.index'));
    }


    public function update(Budget $budget)
    {
        $this->validate(request(), ['category_id' =>'required','budget_date'=>'required','amount'=>'required']);
        $budget->update(request()->all());
        return redirect(route('budgets.index'))->with('success', 'Budget successfully updated');
    }

    public function edit(Budget $budget)
    {
        $categories = Category::all();
        $months = $this->months;
        return view('budgets.edit', compact('budget', 'categories', 'months'));
    }

    public function destroy(Budget $budget)
    {
        $budget->delete();
        return redirect(route('budgets.index'))->with('success', 'Budget successfully deleted');
    }
}

resources/views/budgets/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <form action="{{route('budgets.store')}}" method="POST">
                    {{csrf_field()}}
                    @include('budgets._partials.forms.budget')
                </form>
            </div>

        </div>
    </div>
@stop

resources/views/budgets/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <form action="{{route('budgets.update', $budget->id)}}" method="POST">
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                    @include('budgets._partials.forms.budget', ['actionTitle' => 'Edit Budget', 'buttonTitle' => 'Update'])
                </form>
            </div>

        </div>
    </div>
@stop

resources/views/budgets/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row m-2">
            <div class="col mb-2">
                <div class="float-left">
                    <h3>Monthly Budget</h3>
                </div>
                <div class="float-right">
                    <form method="GET" id="months-form">
                        <select name="month" id="month" class="form-control" onchange="this.form.submit()">
                            @foreach($months as $month)
                                <option value="{{$month}}" @if($currentMonth == $month) selected @endif>{{$month}}</option>
                            @endforeach
                        </select>
                    </form>
                </div>
            </div>
        </div>
        <div class="card jeasy-card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr><th>Category</th><th>Amount</th><th>Balance</th><th colspan="2">Action</th></tr>
                        </thead>
                        <tbody>
                        @foreach($budgets as $budget)
                            <tr>
                                <td>{{ $budget->category->name }}</td>
                                <td>{{ $budget->amount }}</td>
                                <td>{{ $budget->balance() }}</td>
                                <td>
                                    <a href="/budgets/{{ $budget->id }}/edit" class="btn btn-primary btn-xs">Edit</a>
                                </td>
                                <td>
                                    <form action="/budgets/{{ $budget->id }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button class="btn btn-danger btn-xs" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop