routes/web.php
<?php


Auth::routes();

Route::resource('transactions', 'Transactions\TransactionsController', ['except' => ['show']]);
Route::get('/transactions/{category?}', 'Transactions\TransactionsController@index');

Route::resource('categories', 'Categories\CategoriesController')->middleware('auth');

Route::resource('budgets', 'Budgets\BudgetsController')->middleware('auth');

app/Models/Transactions/Category.php
<?php

namespace App\Models\Transactions;

use App\Models\Scopes\UserScope;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug', 'user_id'];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new UserScope);

        static::saving(function($category) {
            $category->user_id = $category->user_id ?: auth()->id();
            $category->slug = $category->slug ?: str_slug($category->name);
        });

        static::updating(function($category) {
            $category->slug =  str_slug($category->name);
        });
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class, 'category_id');
    }
}

app/Http/Controllers/Categories/CategoriesController.php
<?php

namespace App\Http\Controllers\Categories;

use App\Models\Transactions\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{


    public function index()
    {
        $categories = Category::paginate();
        return view('categories.index', compact('categories'));
    }


    public function create()
    {

        return view('categories.create');
    }


    public function store(Request $request)
    {
        $this->validate(request(), [
            'name' => 'required'
        ]);
        Category::create(request()->all());
        return redirect('/categories')->with('success', 'Category Successfully Created');
    }


    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    public function update(Category $category)
    {
        $this->validate(request(), ['name' => 'required']);
        $category->update(request()->all());
        return redirect(route('categories.index'));
    }


    public function destroy(Category $category)
    {
        $category->delete();
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <form action="/categories" method="POST">
                    {{csrf_field()}}
                    @include('categories._partials.forms.category')
                </form>
            </div>

        </div>
    </div>
@stop

resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <form action="{{ route('categories.update', [$category->slug]) }}" method="POST">
                    {{csrf_field()}}
                    {{ method_field('PUT') }}
                    @include('categories._partials.forms.category', ['actionTitle' => 'Edit Category', 'buttonTitle' => 'Update'])
                </form>
            </div>

        </div>
    </div>
@stop

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="card jeasy-card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr><th>Date</th><th>Name</th><th>Slug</th><th colspan="2">Action</th></tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->created_at->format('m/d/Y') }}</td>
                                <td>{{ $category->name }}</td>
                                <td>{{ $category->slug }}</td>
                                <td>
                                    <a href="{{ route('categories.edit', [$category->slug]) }}" class="btn btn-primary btn-xs">Edit</a>
                                </td>
                                <td>
                                    <form action="{{ route('categories.destroy',[$category->slug]) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button class="btn btn-danger btn-xs" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $categories->links() }}
                </div>
            </div>
        </div>
    </div>
@stop